name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo build target
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        env: ${{secrets.DATABASE_URL}}
      - run: cargo build
        working-directory: ./ranked/parser
