name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo build target
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          cargo install sqlx-cli
        working-directory: ./ranked/parser
      - run: |
          RUSTFLAGS="-Z macro-backtrace" cargo sqlx prepare -- --all-targets --all-features
          cargo build
        working-directory: ./ranked/parser
