name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo build target
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build
        working-directory: ./ranked/parser
# .github/workflows/release.yml

#on:
  #push:
    #branches: [main, refactor_rust]

#jobs:
  #release:
    #name: release ${{ matrix.target }}
    #runs-on: ubuntu-latest
    #strategy:
      #fail-fast: false
      #matrix:
        #target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    #steps:
      #- uses: actions/checkout@master
      #- name: Compile and release
        #uses: rust-build/rust-build.action@v1.4.5
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
          #RUSTTARGET: ${{ matrix.target }}
          #EXTRA_FILES: "README.md LICENSE"
