name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo build target
    runs-on: ubuntu-latest
    working_directory: ./ranked/parser
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
