name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo build target
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo install sqlx-cli
        working-directory: ./ranked/parser
      - run: |
          cargo sqlx prepare -- --all-targets --all-features -Z macro-backtrace
          cargo build
        working-directory: ./ranked/parser
